CREATE SCHEMA IF NOT EXISTS server;

DROP TABLE IF EXISTS server.points;

CREATE TABLE server.points (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
                              numberClient INTEGER,
                              shot INTEGER,
                              hit INTEGER
);
